# Generated by Django 6.0.3 on 2026-04-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('aadhar_number', models.CharField(blank=True, max_length=12)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('employee_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('role', models.CharField(choices=[('Teacher', 'Teacher'), ('Principal', 'Principal'), ('Librarian', 'Librarian'), ('Accountant', 'Accountant'), ('Security Guard', 'Security Guard'), ('Driver', 'Driver'), ('Peon', 'Peon'), ('Other', 'Other')], default='Teacher', max_length=20)),
                ('department', models.CharField(blank=True, choices=[('Science', 'Science'), ('Mathematics', 'Mathematics'), ('English', 'English'), ('Hindi', 'Hindi'), ('Social Science', 'Social Science'), ('Computer', 'Computer'), ('Administration', 'Administration'), ('Accounts', 'Accounts'), ('Library', 'Library'), ('Security', 'Security'), ('Transport', 'Transport'), ('Other', 'Other')], max_length=50)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('experience', models.IntegerField(default=0)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('emergency_name', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=15)),
                ('emergency_relation', models.CharField(blank=True, max_length=50)),
                ('iris_image', models.ImageField(blank=True, null=True, upload_to='iris/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
