# Generated by Django 6.0.3 on 2026-04-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_teacher'),
        ('teachers', '0002_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
