# Generated by Django 6.0.3 on 2026-04-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_delete_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
